apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: recommendation
      version: v2
    name: recommendation-v2
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: recommendation
      version: v2
    name: recommendation-v2
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: recommendation-v2:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: recommendation/java/vertx
      git:
        uri: https://github.com/eformat/istio-tutorial
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-java:latest
      type: Source
    triggers:
    - github:
        secret: jzSpXCWEMHEg6iMq4YsW
      type: GitHub
    - generic:
        secret: XwSt7EopYKdgYO61Jaxo
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: recommendation
      version: v2
    name: recommendation-v2
  spec:
    replicas: 1
    selector:
      app: recommendation
      deploymentconfig: recommendation-v2
      version: v2
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: recommendation
          deploymentconfig: recommendation-v2
          version: v2
      spec:
        containers:
        - env:
          - name: JAEGER_ENDPOINT
            value: http://jaeger-collector.istio-system.svc:14268/api/traces
          - name: JAEGER_PROPAGATION
            value: b3
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SERVICE_NAME
            value: recommendation
          - name: JAVA_OPTIONS
            value: -Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true
          image: recommendation-v2:latest
          name: recommendation-v2
          ports:
          - containerPort: 8778
            protocol: TCP
          - containerPort: 9779
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - recommendation-v2
        from:
          kind: ImageStreamTag
          name: recommendation-v2:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: recommendation
      version: v2
    name: recommendation-v2
  spec:
    ports:
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    - name: 9779-tcp
      port: 9779
      protocol: TCP
      targetPort: 9779
    selector:
      app: recommendation
      deploymentconfig: recommendation-v2
      version: v2
  status:
    loadBalancer: {}
kind: List
metadata: {}
